dist: trusty
language: go

go:
  - "1.11"

go_import_path: wio

before_install:
  - source wenv
  - sudo apt-get update
  - sudo apt-get install gcc-avr avr-libc avrdude
  - sudo apt-get install libboost-system-dev libboost-thread-dev libboost-coroutine-dev
  - go get github.com/magefile/mage
install:
  - mage setup

script:
  - mage build
  - mage fmtLint
  - go test -v ./...
  - ./wmake test
